apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: lucee-docker
      manager: oc
      operation: Update
    name: lucee-docker
    namespace: lucee-app
  spec:
    clusterIP: 172.30.28.242
    clusterIPs:
    - 172.30.28.242
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: lucee-docker
      deploymentconfig: lucee-docker
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
