apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    labels:
      build: lucee-docker
    name: lucee-docker
    namespace: lucee-app
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: lucee-docker:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy:
        env:
        - name: LUCEE_ADMIN_PASSWORD
          value: changeit
        - name: LUCEE_EXTENSIONS
          value: 3F9DFF32-B555-449D-B0EB5DB723044045;name=WebSocket
        - name: LUCEE_VERSION
          value: 5.3.7.34-RC
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: QZBQbMe4ZAXpCcwUSwbD
      type: GitHub
    - generic:
        secret: XSf1TCYNne8XHdTKu2i9
      type: Generic
  status:
    lastVersion: 12
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
