apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  extensions:
    - >-
      https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: false
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: argocd
  labels:
    app: keycloak
spec:
  realm:
    id: argocd
    realm: argocd
    enabled: true
    displayName: ArgoCD Realm
    clientScopes:
      - name: groups
        protocol: openid-connect
        protocolMappers:
          - name: groups
            protocol: openid-connect
            consentRequired: false
            protocolMapper: oidc-group-membership-mapper
            config:
              "full.path": "false"
              "id.token.claim": "true"
              "access.token.claim": "true"
              "userinfo.token.claim": "true"
              "claim.name": groups            
      - name: email
        protocol: openid-connect
        protocolMappers:
          - name: email
            protocol: openid-connect
            consentRequired: false
            protocolMapper: oidc-usermodel-property-mapper
            config:
              "id.token.claim": "true"
              "access.token.claim": "true"
              "userinfo.token.claim": "true"
              "claim.name": email
              "jsonType.label": String
              "user.attribute": email
    # scopeMappings:
    #   - client: argocd
    #     clientScope: groups
  instanceSelector:
    matchLabels:
      app: keycloak
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: argocd
  labels:
    app: keycloak
spec:
  realmSelector:
    matchLabels:
      app: keycloak
  client:    
    id: argocd
    clientId: argocd
    name: argocd
    enabled: true
    clientAuthenticatorType: client-secret
    redirectUris:
      - https://example-server-example-argocd.apps.cluster-2b6f.2b6f.sandbox1326.opentlc.com/auth/callback
    rootUrl: https://example-server-example-argocd.apps.cluster-2b6f.2b6f.sandbox1326.opentlc.com
    adminUrl: https://example-server-example-argocd.apps.cluster-2b6f.2b6f.sandbox1326.opentlc.com
    webOrigins:
      - https://example-server-example-argocd.apps.cluster-2b6f.2b6f.sandbox1326.opentlc.com
    notBefore: 0
    surrogateAuthRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    publicClient: false
    frontchannelLogout: false
    protocol: openid-connect
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    access:
      view: true
      configure: true
      manage: true
    defaultClientScopes:
      - groups
      - email
    bearerOnly: false
